// GENERATED by the simbolik token build — do not edit. Source: simbolik/tokens/. Rebuild with: npm run tokens:build

/** The three context switches and how each reaches CSS. */
export const contexts = {
  "theme": {
    "values": [
      "light",
      "dark"
    ],
    "default": "light",
    "attribute": "data-theme"
  },
  "density": {
    "values": [
      "comfortable",
      "compact"
    ],
    "default": "comfortable",
    "attribute": "data-density"
  },
  "text-size": {
    "values": [
      "min",
      "max"
    ],
    "default": "min",
    "media": {
      "max": "(min-width: 768px)"
    }
  }
} as const;

/** Primitive tokens: raw, context-free values. Never consumed by components. */
export const primitive = {
  "color": {
    "frost": {
      "50": "#f9fafb",
      "100": "#f3f5f8",
      "200": "#e7ebf0",
      "300": "#dae1e9",
      "400": "#ced7e1",
      "500": "#c2cdda",
      "600": "#aebccd",
      "700": "#99abc0",
      "800": "#8599b2",
      "900": "#7088a5",
      "1000": "#5c7798"
    },
    "moonrise": {
      "100": "#b2becd",
      "200": "#92a1b2",
      "300": "#728396",
      "400": "#52667b",
      "500": "#324860",
      "600": "#283a4d",
      "650": "#243445",
      "700": "#1e2b3a",
      "800": "#141d26",
      "850": "#0f161d",
      "900": "#0a0e13"
    },
    "midnight": {
      "50": "#ebebec",
      "100": "#d7d8d9",
      "150": "#c3c4c6",
      "200": "#afb1b3",
      "300": "#88898c",
      "400": "#606266",
      "500": "#383b40",
      "600": "#2d2f33",
      "700": "#222326",
      "800": "#16181a",
      "850": "#111213",
      "900": "#0b0c0d"
    },
    "steel": {
      "400": "#cedae0",
      "500": "#c2d1d8",
      "600": "#a4b4bb",
      "700": "#86969e",
      "800": "#697980",
      "850": "#5a6a72",
      "900": "#4b5b63",
      "950": "#3c4d55",
      "1000": "#2d3e46"
    },
    "red": {
      "50": "#fee7e7",
      "100": "#fccfcf",
      "200": "#fa9f9f",
      "300": "#f77070",
      "400": "#f54040",
      "500": "#f21010",
      "550": "#cc0d0d",
      "600": "#c20d0d",
      "700": "#910a0a",
      "800": "#610606",
      "900": "#300303"
    },
    "blue": {
      "50": "#e9eafc",
      "100": "#d3d6fa",
      "200": "#a7adf5",
      "300": "#7a84ef",
      "400": "#4e5bea",
      "500": "#2232e5",
      "550": "#1f2ed4",
      "600": "#1b28b7",
      "700": "#141e89",
      "800": "#0e145c",
      "900": "#070a2e"
    },
    "green": {
      "50": "#ecfce9",
      "100": "#dafad3",
      "200": "#b5f5a7",
      "300": "#90ef7a",
      "400": "#6bea4e",
      "500": "#46e522",
      "600": "#38b71b",
      "700": "#2a8914",
      "800": "#1c5c0e",
      "850": "#15450a",
      "900": "#0e2e07"
    },
    "orange": {
      "50": "#feeee6",
      "100": "#fcddcd",
      "200": "#fabc9b",
      "300": "#f79a68",
      "400": "#f57936",
      "500": "#f25704",
      "600": "#c24603",
      "700": "#913402",
      "800": "#612302",
      "850": "#491a01",
      "900": "#301101"
    },
    "yellow": {
      "50": "#fefce8",
      "100": "#fcf9d0",
      "200": "#faf3a1",
      "300": "#f7ec73",
      "400": "#f5e644",
      "500": "#f2e015",
      "550": "#e5d414",
      "600": "#c2b311",
      "700": "#91860d",
      "800": "#615a08",
      "850": "#494306",
      "900": "#302d04"
    },
    "alpha": {
      "white": {
        "5": "#ffffff0d",
        "10": "#ffffff1a",
        "15": "#ffffff26",
        "20": "#ffffff33",
        "30": "#ffffff4d",
        "40": "#ffffff66",
        "50": "#ffffff80",
        "60": "#ffffff99",
        "70": "#ffffffb3",
        "80": "#ffffffcc",
        "90": "#ffffffe6",
        "100": "#ffffff"
      },
      "black": {
        "5": "#0000000d",
        "10": "#0000001a",
        "15": "#00000026",
        "20": "#00000033",
        "30": "#0000004d",
        "40": "#00000066",
        "50": "#00000080",
        "60": "#00000099",
        "70": "#000000b3",
        "80": "#000000cc",
        "90": "#000000e6",
        "100": "#000000"
      },
      "red": {
        "20": "#cc0d0d33",
        "30": "#cc0d0d4d",
        "40": "#cc0d0d66",
        "50": "#cc0d0d80",
        "60": "#cc0d0d99"
      },
      "frost": {
        "10": "#5c77981a",
        "15": "#5c779826",
        "20": "#5c779833",
        "25": "#5c779840",
        "30": "#5c77984d",
        "35": "#5c779859",
        "40": "#5c779866",
        "45": "#5c779873",
        "50": "#5c779880"
      },
      "moonrise": {
        "5": "#3248600d",
        "10": "#3248601a",
        "15": "#32486026",
        "20": "#32486033",
        "25": "#32486040",
        "30": "#3248604d",
        "35": "#32486059",
        "40": "#32486066",
        "45": "#32486073",
        "50": "#32486080"
      }
    }
  },
  "space": {
    "0": "0px",
    "2": "2px",
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "20": "20px",
    "24": "24px",
    "28": "28px",
    "32": "32px",
    "36": "36px",
    "40": "40px",
    "48": "48px",
    "56": "56px",
    "64": "64px",
    "72": "72px",
    "80": "80px",
    "88": "88px",
    "96": "96px"
  },
  "size": {
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "20": "20px",
    "24": "24px",
    "28": "28px",
    "32": "32px",
    "40": "40px",
    "44": "44px",
    "48": "48px",
    "56": "56px",
    "64": "64px",
    "72": "72px",
    "80": "80px",
    "88": "88px",
    "96": "96px",
    "viewport": {
      "320": "320px",
      "640": "640px",
      "768": "768px",
      "1024": "1024px",
      "1280": "1280px",
      "1440": "1440px"
    },
    "content": {
      "480": "480px",
      "720": "720px",
      "960": "960px",
      "1360": "1360px"
    }
  },
  "radius": {
    "2": "2px",
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "12": "12px",
    "16": "16px",
    "9999": "9999px"
  },
  "border-width": {
    "1": "1px",
    "2": "2px",
    "3": "3px"
  },
  "font": {
    "family": {
      "display": "Funnel Display",
      "body": "Geist",
      "mono": "Geist Mono"
    },
    "size": {
      "12": "12px",
      "14": "14px",
      "16": "16px",
      "18": "18px",
      "20": "20px",
      "24": "24px",
      "28": "28px",
      "32": "32px",
      "40": "40px",
      "48": "48px",
      "56": "56px",
      "64": "64px",
      "72": "72px",
      "88": "88px"
    },
    "weight": {
      "light": 300,
      "regular": 400,
      "medium": 500,
      "semibold": 600
    },
    "letter-spacing": {
      "tighter": "-3px",
      "tight": "-2px",
      "snug": "-1px",
      "none": "0px",
      "loose": "0.5px",
      "looser": "1px",
      "caps": "4px"
    }
  },
  "opacity": {
    "media": {
      "disabled": 0.5
    }
  },
  "blur": {
    "4": "4px",
    "8": "8px",
    "14": "14px"
  },
  "duration": {
    "80": "80ms",
    "150": "150ms",
    "200": "200ms",
    "320": "320ms",
    "1000": "1000ms",
    "1600": "1600ms",
    "2400": "2400ms",
    "22000": "22000ms"
  },
  "easing": {
    "expo-out": "cubic-bezier(0.16, 1, 0.3, 1)",
    "expo-in": "cubic-bezier(0.7, 0, 0.84, 0)",
    "cubic-in-out": "cubic-bezier(0.65, 0, 0.35, 1)"
  }
} as const;

/** Semantic tokens. A value that changes with a context is an object keyed by that context's values. */
export const semantic = {
  "radius": {
    "control": {
      "xs": "2px",
      "sm": "4px",
      "md": "6px",
      "lg": "8px"
    },
    "container": {
      "sm": "8px",
      "md": "12px",
      "lg": "16px"
    },
    "inset": "2px",
    "full": "9999px"
  },
  "border-width": {
    "hairline": "1px",
    "default": "2px",
    "thick": "3px"
  },
  "size": {
    "icon": {
      "xs": "12px",
      "sm": "16px",
      "md": "20px",
      "lg": "24px",
      "xl": "32px",
      "2xl": "40px"
    },
    "target": {
      "min": "24px",
      "comfortable": "44px"
    },
    "display": {
      "xs": "8px",
      "sm": "16px",
      "md": "20px",
      "lg": "24px",
      "xl": "32px"
    },
    "selection": {
      "sm": "16px",
      "md": "20px",
      "lg": "24px"
    },
    "content": {
      "sm": "480px",
      "md": "720px",
      "lg": "960px",
      "xl": "1360px"
    },
    "sidebar": {
      "width": "280px"
    },
    "modal": {
      "sm": "400px",
      "md": "560px",
      "lg": "800px"
    },
    "drawer": {
      "width": "384px"
    },
    "dropdown": {
      "width": "240px"
    },
    "command-palette": {
      "width": "640px"
    },
    "search": {
      "width": "320px"
    },
    "preview": {
      "narrow": "360px"
    },
    "table-of-contents": {
      "width": "240px"
    },
    "popover": {
      "width": "320px"
    },
    "control": {
      "xs": "24px",
      "sm": {
        "comfortable": "32px",
        "compact": "28px"
      },
      "md": {
        "comfortable": "40px",
        "compact": "32px"
      },
      "lg": {
        "comfortable": "48px",
        "compact": "40px"
      }
    }
  },
  "focus": {
    "ring": {
      "width": "2px",
      "offset": "2px"
    }
  },
  "typography": {
    "display-1": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "56px",
        "max": "88px"
      },
      "fontWeight": 400,
      "lineHeight": 1,
      "letterSpacing": "0px"
    },
    "display-2": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "48px",
        "max": "72px"
      },
      "fontWeight": 400,
      "lineHeight": 1,
      "letterSpacing": "0px"
    },
    "h1": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "40px",
        "max": "56px"
      },
      "fontWeight": 400,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    },
    "h2": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "32px",
        "max": "48px"
      },
      "fontWeight": 400,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    },
    "h3": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "28px",
        "max": "40px"
      },
      "fontWeight": 400,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    },
    "h4": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "24px",
        "max": "32px"
      },
      "fontWeight": 400,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    },
    "h5": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "20px",
        "max": "28px"
      },
      "fontWeight": 400,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    },
    "h6": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "20px",
        "max": "24px"
      },
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "subtitle": {
      "fontFamily": "Geist",
      "fontSize": "20px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "subheading": {
      "fontFamily": "Geist",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-l": {
      "fontFamily": "Geist",
      "fontSize": "20px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-m": {
      "fontFamily": "Geist",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-s": {
      "fontFamily": "Geist",
      "fontSize": "14px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-t": {
      "fontFamily": "Geist",
      "fontSize": "12px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "label-l": {
      "fontFamily": "Geist Mono",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.4,
      "letterSpacing": "0px",
      "textTransform": "uppercase"
    },
    "label-m": {
      "fontFamily": "Geist Mono",
      "fontSize": "14px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": "0.5px",
      "textTransform": "uppercase"
    },
    "label-s": {
      "fontFamily": "Geist Mono",
      "fontSize": "12px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": "0.5px",
      "textTransform": "uppercase"
    },
    "body-l-bold": {
      "fontFamily": "Geist",
      "fontSize": "20px",
      "fontWeight": 700,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-m-bold": {
      "fontFamily": "Geist",
      "fontSize": "16px",
      "fontWeight": 700,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-s-bold": {
      "fontFamily": "Geist",
      "fontSize": "14px",
      "fontWeight": 700,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-m-medium": {
      "fontFamily": "Geist",
      "fontSize": "16px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-m-semibold": {
      "fontFamily": "Geist",
      "fontSize": "16px",
      "fontWeight": 600,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-s-semibold": {
      "fontFamily": "Geist",
      "fontSize": "14px",
      "fontWeight": 600,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "body-l-light": {
      "fontFamily": "Geist",
      "fontSize": "20px",
      "fontWeight": 300,
      "lineHeight": 1.4,
      "letterSpacing": "0px"
    },
    "h4-light": {
      "fontFamily": "Funnel Display",
      "fontSize": {
        "min": "24px",
        "max": "32px"
      },
      "fontWeight": 300,
      "lineHeight": 1.2,
      "letterSpacing": "0px"
    }
  },
  "elevation": {
    "0": {
      "light": "0px 0px 1px 0px #3248600d, 0px 1px 2px 0px #3248601a, 0px 2px 4px 0px #3248600d",
      "dark": "0px 0px 1px 0px #0000001a, 0px 1px 2px 0px #00000026, 0px 2px 4px 0px #0000001a"
    },
    "1": {
      "light": "0px 2px 8px 1px #3248601a, 0px 1px 2px 0px #3248601a",
      "dark": "0px 2px 8px 1px #00000026, 0px 1px 2px 0px #00000026"
    },
    "2": {
      "light": "0px 4px 16px 1px #3248601a, 0px 2px 4px 0px #3248601a",
      "dark": "0px 4px 16px 1px #00000026, 0px 2px 4px 0px #00000026"
    },
    "3": {
      "light": "0px 12px 16px 2px #3248601a, 0px 2px 8px 0px #32486026",
      "dark": "0px 12px 16px 2px #00000026, 0px 2px 8px 0px #00000033"
    },
    "inset": {
      "light": "inset 0px 0px 1px 0px #3248604d",
      "dark": "inset 0px 0px 1px 0px #00000066"
    },
    "inset-2": {
      "light": "inset -1px 2px 2px 0px #32486033",
      "dark": "inset -1px 2px 2px 0px #0000004d"
    }
  },
  "layer": {
    "base": 0,
    "raised": 1000,
    "sticky": 1100,
    "overlay": 1200,
    "modal": 1300,
    "critical": 1400
  },
  "breakpoint": {
    "text-size": "768px",
    "layout": "768px",
    "side-columns": "1280px"
  },
  "font": {
    "weight": {
      "bold": 700
    }
  },
  "motion": {
    "feedback": {
      "duration": "150ms",
      "easing": "cubic-bezier(0.16, 1, 0.3, 1)"
    },
    "state": {
      "duration": "200ms",
      "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
    },
    "enter": {
      "duration": "320ms",
      "easing": "cubic-bezier(0.16, 1, 0.3, 1)"
    },
    "exit": {
      "duration": "200ms",
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
    },
    "stagger": {
      "delay": "80ms"
    },
    "hover": {
      "open-delay": "80ms",
      "close-delay": "320ms"
    },
    "marquee": {
      "duration": "22000ms"
    },
    "live-pulse": {
      "duration": "2400ms",
      "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
    },
    "loading": {
      "duration": "1600ms",
      "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
    },
    "cursor": {
      "duration": "1000ms"
    },
    "ambient": {
      "duration": "1600ms",
      "easing": "cubic-bezier(0.65, 0, 0.35, 1)"
    }
  },
  "color": {
    "surface": {
      "canvas": {
        "light": "#e7ebf0",
        "dark": "#111213"
      },
      "default": {
        "light": "#f3f5f8",
        "dark": "#16181a"
      },
      "default-disabled": {
        "light": "#ebebec",
        "dark": "#383b40"
      },
      "raised": {
        "light": "#f9fafb",
        "dark": "#222326"
      },
      "brand": {
        "light": "#cc0d0d",
        "dark": "#f21010"
      },
      "inverse": {
        "light": "#243445",
        "dark": "#e7ebf0"
      },
      "sunken": {
        "light": "#e7ebf0",
        "dark": "#111213"
      },
      "overlay": {
        "light": "#ffffff66",
        "dark": "#00000066"
      },
      "overlay-subtle": {
        "light": "#ffffff26",
        "dark": "#00000026"
      }
    },
    "text": {
      "default": {
        "light": "#1e2b3a",
        "dark": "#cedae0"
      },
      "subtle": {
        "light": "#52667b",
        "dark": "#a4b4bb"
      },
      "subtlest": {
        "light": "#5a6a72",
        "dark": "#86969e"
      },
      "disabled": "#88898c",
      "brand": {
        "light": "#cc0d0d",
        "dark": "#f21010"
      },
      "brand-hover": {
        "light": "#910a0a",
        "dark": "#f54040"
      },
      "accent": {
        "light": "#0e145c",
        "dark": "#c2b311"
      },
      "accent-hover": {
        "light": "#1f2ed4",
        "dark": "#f5e644"
      },
      "inverse": {
        "light": "#f9fafb",
        "dark": "#1e2b3a"
      },
      "on-brand": "#f9fafb",
      "on-media": "#f9fafb",
      "selected": "#f9fafb",
      "link": {
        "light": "#1e2b3a",
        "dark": "#cedae0"
      },
      "link-hover": {
        "light": "#0f161d",
        "dark": "#ebebec"
      },
      "link-pressed": {
        "light": "#324860",
        "dark": "#c2d1d8"
      },
      "link-underline": {
        "light": "#52667b",
        "dark": "#a4b4bb"
      },
      "link-underline-hover": {
        "light": "#1e2b3a",
        "dark": "#cedae0"
      },
      "link-disabled": {
        "light": "#52667b",
        "dark": "#a4b4bb"
      }
    },
    "border": {
      "subtle": {
        "light": "#ced7e1",
        "dark": "#2d2f33"
      },
      "strong": {
        "light": "#99abc0",
        "dark": "#383b40"
      },
      "control": {
        "light": "#7088a5",
        "dark": "#88898c"
      },
      "control-hover": {
        "light": "#5c7798",
        "dark": "#383b40"
      },
      "control-disabled": {
        "light": "#d7d8d9",
        "dark": "#606266"
      },
      "control-selected": {
        "light": "#ffffff1a",
        "dark": "#ffffff80"
      },
      "focus": {
        "light": "#cc0d0d",
        "dark": "#f21010"
      },
      "focus-field": {
        "light": "#1f2ed4",
        "dark": "#f5e644"
      },
      "brand": {
        "light": "#cc0d0d",
        "dark": "#f21010"
      },
      "inverse": {
        "light": "#1e2b3a",
        "dark": "#f9fafb"
      },
      "edge-top": {
        "light": "#ced7e1",
        "dark": "#000000e6"
      },
      "edge-bottom": {
        "light": "#ffffff",
        "dark": "#ffffff0d"
      },
      "edge-highlight": {
        "light": "#ffffffe6",
        "dark": "#ffffff1a"
      },
      "edge-highlight-subtle": {
        "light": "#ffffff33",
        "dark": "#ffffff0d"
      },
      "edge-shade": {
        "light": "#00000033",
        "dark": "#00000066"
      },
      "edge-shade-subtle": {
        "light": "#0000001a",
        "dark": "#00000033"
      }
    },
    "action": {
      "brand": {
        "background": "#cc0d0d",
        "background-hover": "#910a0a",
        "background-pressed": "#910a0a",
        "background-disabled": {
          "light": "#cc0d0d66",
          "dark": "#cc0d0d80"
        },
        "foreground": "#f9fafb",
        "foreground-disabled": "#ffffff4d",
        "border": "#ffffff1a",
        "border-hover": "#0000000d",
        "border-disabled": "#0000000d"
      },
      "default": {
        "background": {
          "light": "#f3f5f8",
          "dark": "#2d2f33"
        },
        "background-hover": {
          "light": "#dae1e9",
          "dark": "#383b40"
        },
        "background-pressed": {
          "light": "#dae1e9",
          "dark": "#383b40"
        },
        "background-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        },
        "foreground": {
          "light": "#243445",
          "dark": "#c2d1d8"
        },
        "foreground-hover": {
          "light": "#cc0d0d",
          "dark": "#f21010"
        },
        "foreground-disabled": {
          "light": "#88898c",
          "dark": "#606266"
        },
        "border": {
          "light": "#f9fafb",
          "dark": "#383b40"
        },
        "border-hover": {
          "light": "#aebccd",
          "dark": "#606266"
        },
        "border-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        }
      },
      "secondary": {
        "background": {
          "light": "#32486026",
          "dark": "#5c779833"
        },
        "background-hover": {
          "light": "#32486040",
          "dark": "#5c779859"
        },
        "background-pressed": {
          "light": "#32486033",
          "dark": "#5c779840"
        },
        "background-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        },
        "foreground": {
          "light": "#243445",
          "dark": "#c2cdda"
        },
        "foreground-disabled": {
          "light": "#88898c",
          "dark": "#606266"
        },
        "border": {
          "light": "#ffffff4d",
          "dark": "#ffffff1a"
        },
        "border-hover": {
          "light": "#ffffff4d",
          "dark": "#ffffff1a"
        },
        "border-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        }
      },
      "tertiary": {
        "background": {
          "light": "#f9fafb",
          "dark": "#222326"
        },
        "background-hover": {
          "light": "#c2cdda",
          "dark": "#16181a"
        },
        "background-pressed": {
          "light": "#c2cdda",
          "dark": "#16181a"
        },
        "background-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        },
        "foreground": {
          "light": "#243445",
          "dark": "#c2cdda"
        },
        "foreground-disabled": {
          "light": "#88898c",
          "dark": "#606266"
        },
        "border": {
          "light": "#ffffffe6",
          "dark": "#ffffff1a"
        },
        "border-hover": {
          "light": "#c2cdda",
          "dark": "#0b0c0d"
        },
        "border-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        }
      },
      "outline": {
        "border": {
          "light": "#b2becd",
          "dark": "#383b40"
        },
        "border-hover": {
          "light": "#92a1b2",
          "dark": "#606266"
        },
        "border-pressed": {
          "light": "#92a1b2",
          "dark": "#606266"
        },
        "border-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        },
        "foreground": {
          "light": "#243445",
          "dark": "#cedae0"
        },
        "foreground-disabled": {
          "light": "#afb1b3",
          "dark": "#606266"
        },
        "background-hover": {
          "light": "#dae1e9",
          "dark": "#222326"
        },
        "background-pressed": {
          "light": "#dae1e9",
          "dark": "#222326"
        }
      },
      "ghost": {
        "background-hover": {
          "light": "#c2cdda",
          "dark": "#383b40"
        },
        "background-pressed": {
          "light": "#c2cdda",
          "dark": "#383b40"
        },
        "foreground": {
          "light": "#243445",
          "dark": "#c2cdda"
        },
        "foreground-disabled": {
          "light": "#88898c",
          "dark": "#606266"
        }
      },
      "inverse": {
        "background": {
          "light": "#243445",
          "dark": "#f3f5f8"
        },
        "background-hover": {
          "light": "#1e2b3a",
          "dark": "#dae1e9"
        },
        "background-pressed": {
          "light": "#1e2b3a",
          "dark": "#dae1e9"
        },
        "background-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        },
        "foreground": {
          "light": "#f9fafb",
          "dark": "#1e2b3a"
        },
        "foreground-disabled": {
          "light": "#88898c",
          "dark": "#606266"
        },
        "border": {
          "light": "#283a4d",
          "dark": "#f9fafb"
        },
        "border-hover": {
          "light": "#243445",
          "dark": "#aebccd"
        },
        "border-disabled": {
          "light": "#c3c4c6",
          "dark": "#2d2f33"
        }
      },
      "destructive": {
        "background": {
          "light": "#fccfcf",
          "dark": "#610606"
        },
        "background-hover": {
          "light": "#fa9f9f",
          "dark": "#910a0a"
        },
        "background-pressed": {
          "light": "#fa9f9f",
          "dark": "#910a0a"
        },
        "background-disabled": "#cc0d0d4d",
        "foreground": {
          "light": "#910a0a",
          "dark": "#fccfcf"
        },
        "foreground-hover": {
          "light": "#610606",
          "dark": "#fee7e7"
        },
        "foreground-disabled": "#cc0d0d80",
        "border": "#0000000d",
        "border-hover": {
          "light": "#cc0d0d4d",
          "dark": "#f77070"
        },
        "border-disabled": "#0000000d"
      }
    },
    "feedback": {
      "info": {
        "surface": {
          "light": "#1f2ed4",
          "dark": "#4e5bea"
        },
        "surface-subtle": {
          "light": "#e9eafc",
          "dark": "#0e145c"
        },
        "text-on-surface": {
          "light": "#e9eafc",
          "dark": "#f9fafb"
        },
        "text-on-subtle": {
          "light": "#2232e5",
          "dark": "#d3d6fa"
        },
        "border": {
          "light": "#7a84ef",
          "dark": "#4e5bea"
        },
        "border-subtle": {
          "light": "#d3d6fa",
          "dark": "#141e89"
        }
      },
      "warning": {
        "surface": {
          "light": "#c24603",
          "dark": "#f57936"
        },
        "surface-subtle": {
          "light": "#feeee6",
          "dark": "#491a01"
        },
        "text-on-surface": {
          "light": "#f9fafb",
          "dark": "#301101"
        },
        "text-on-subtle": {
          "light": "#913402",
          "dark": "#fabc9b"
        },
        "border": {
          "light": "#f79a68",
          "dark": "#f25704"
        },
        "border-subtle": {
          "light": "#fabc9b",
          "dark": "#612302"
        }
      },
      "success": {
        "surface": {
          "light": "#1c5c0e",
          "dark": "#38b71b"
        },
        "surface-subtle": {
          "light": "#ecfce9",
          "dark": "#15450a"
        },
        "text-on-surface": {
          "light": "#ecfce9",
          "dark": "#0e2e07"
        },
        "text-on-subtle": {
          "light": "#1c5c0e",
          "dark": "#b5f5a7"
        },
        "border": {
          "light": "#38b71b",
          "dark": "#2a8914"
        },
        "border-subtle": {
          "light": "#b5f5a7",
          "dark": "#1c5c0e"
        }
      },
      "danger": {
        "surface": {
          "light": "#c20d0d",
          "dark": "#f54040"
        },
        "surface-subtle": {
          "light": "#fee7e7",
          "dark": "#610606"
        },
        "text-on-surface": {
          "light": "#fee7e7",
          "dark": "#300303"
        },
        "text-on-subtle": {
          "light": "#c20d0d",
          "dark": "#fccfcf"
        },
        "border": {
          "light": "#f77070",
          "dark": "#f21010"
        },
        "border-subtle": {
          "light": "#fa9f9f",
          "dark": "#910a0a"
        }
      }
    },
    "overlay": {
      "scrim": {
        "light": "#00000080",
        "dark": "#00000099"
      }
    },
    "shadow": {
      "xs": {
        "light": "#3248600d",
        "dark": "#0000001a"
      },
      "s": {
        "light": "#3248601a",
        "dark": "#00000026"
      },
      "m": {
        "light": "#32486026",
        "dark": "#00000033"
      },
      "l": {
        "light": "#32486033",
        "dark": "#0000004d"
      },
      "xl": {
        "light": "#3248604d",
        "dark": "#00000066"
      }
    },
    "icon": {
      "default": {
        "light": "#1e2b3a",
        "dark": "#cedae0"
      },
      "subtle": {
        "light": "#52667b",
        "dark": "#a4b4bb"
      },
      "disabled": {
        "light": "#afb1b3",
        "dark": "#606266"
      },
      "inverse": {
        "light": "#f9fafb",
        "dark": "#1e2b3a"
      }
    }
  },
  "space": {
    "inset": {
      "2xs": "2px",
      "xs": "4px",
      "sm": {
        "comfortable": "6px",
        "compact": "4px"
      },
      "md": {
        "comfortable": "8px",
        "compact": "6px"
      },
      "lg": {
        "comfortable": "12px",
        "compact": "8px"
      },
      "xl": {
        "comfortable": "16px",
        "compact": "12px"
      },
      "2xl": {
        "comfortable": "24px",
        "compact": "16px"
      },
      "3xl": {
        "comfortable": "32px",
        "compact": "24px"
      }
    },
    "stack": {
      "xs": "4px",
      "sm": {
        "comfortable": "8px",
        "compact": "6px"
      },
      "md": {
        "comfortable": "12px",
        "compact": "8px"
      },
      "lg": {
        "comfortable": "16px",
        "compact": "12px"
      },
      "xl": {
        "comfortable": "24px",
        "compact": "16px"
      },
      "2xl": {
        "comfortable": "32px",
        "compact": "24px"
      },
      "3xl": {
        "comfortable": "40px",
        "compact": "32px"
      },
      "4xl": {
        "comfortable": "48px",
        "compact": "40px"
      },
      "5xl": {
        "comfortable": "56px",
        "compact": "48px"
      }
    },
    "inline": {
      "xs": "4px",
      "sm": {
        "comfortable": "6px",
        "compact": "4px"
      },
      "md": {
        "comfortable": "8px",
        "compact": "6px"
      },
      "lg": {
        "comfortable": "12px",
        "compact": "8px"
      },
      "xl": {
        "comfortable": "16px",
        "compact": "12px"
      },
      "2xl": {
        "comfortable": "24px",
        "compact": "16px"
      },
      "3xl": {
        "comfortable": "32px",
        "compact": "24px"
      }
    },
    "section": {
      "sm": {
        "comfortable": "48px",
        "compact": "32px"
      },
      "md": {
        "comfortable": "64px",
        "compact": "48px"
      },
      "lg": {
        "comfortable": "96px",
        "compact": "64px"
      }
    },
    "gutter": {
      "xs": {
        "comfortable": "8px",
        "compact": "4px"
      },
      "sm": {
        "comfortable": "12px",
        "compact": "8px"
      }
    }
  },
  "text": {
    "display-xl": {
      "min": "56px",
      "max": "88px"
    },
    "display-lg": {
      "min": "48px",
      "max": "72px"
    },
    "heading-xl": {
      "min": "40px",
      "max": "56px"
    },
    "heading-lg": {
      "min": "32px",
      "max": "48px"
    },
    "heading-md": {
      "min": "28px",
      "max": "40px"
    },
    "heading-sm": {
      "min": "24px",
      "max": "32px"
    },
    "heading-xs": {
      "min": "20px",
      "max": "28px"
    },
    "heading-2xs": {
      "min": "20px",
      "max": "24px"
    },
    "body-lg": "20px",
    "body-md": "16px",
    "body-sm": "14px",
    "body-xs": "12px",
    "label-lg": "16px",
    "label-md": "14px",
    "label-sm": "12px"
  }
} as const;

/** Token path -> CSS custom property name, for every token that reaches CSS. Typography tokens map to one name per part. */
export const cssVariables = {
  "space.0": "--smbk-space-0",
  "space.2": "--smbk-space-2",
  "space.4": "--smbk-space-4",
  "space.6": "--smbk-space-6",
  "space.8": "--smbk-space-8",
  "space.12": "--smbk-space-12",
  "space.16": "--smbk-space-16",
  "space.20": "--smbk-space-20",
  "space.24": "--smbk-space-24",
  "space.28": "--smbk-space-28",
  "space.32": "--smbk-space-32",
  "space.36": "--smbk-space-36",
  "space.40": "--smbk-space-40",
  "space.48": "--smbk-space-48",
  "space.56": "--smbk-space-56",
  "space.64": "--smbk-space-64",
  "space.72": "--smbk-space-72",
  "space.80": "--smbk-space-80",
  "space.88": "--smbk-space-88",
  "space.96": "--smbk-space-96",
  "size.4": "--smbk-size-4",
  "size.6": "--smbk-size-6",
  "size.8": "--smbk-size-8",
  "size.12": "--smbk-size-12",
  "size.16": "--smbk-size-16",
  "size.20": "--smbk-size-20",
  "size.24": "--smbk-size-24",
  "size.28": "--smbk-size-28",
  "size.32": "--smbk-size-32",
  "size.40": "--smbk-size-40",
  "size.44": "--smbk-size-44",
  "size.48": "--smbk-size-48",
  "size.56": "--smbk-size-56",
  "size.64": "--smbk-size-64",
  "size.72": "--smbk-size-72",
  "size.80": "--smbk-size-80",
  "size.88": "--smbk-size-88",
  "size.96": "--smbk-size-96",
  "size.viewport.320": "--smbk-size-viewport-320",
  "size.viewport.640": "--smbk-size-viewport-640",
  "size.viewport.768": "--smbk-size-viewport-768",
  "size.viewport.1024": "--smbk-size-viewport-1024",
  "size.viewport.1280": "--smbk-size-viewport-1280",
  "size.viewport.1440": "--smbk-size-viewport-1440",
  "size.content.480": "--smbk-size-content-480",
  "size.content.720": "--smbk-size-content-720",
  "size.content.960": "--smbk-size-content-960",
  "size.content.1360": "--smbk-size-content-1360",
  "radius.2": "--smbk-radius-2",
  "radius.4": "--smbk-radius-4",
  "radius.6": "--smbk-radius-6",
  "radius.8": "--smbk-radius-8",
  "radius.12": "--smbk-radius-12",
  "radius.16": "--smbk-radius-16",
  "radius.9999": "--smbk-radius-9999",
  "border-width.1": "--smbk-border-width-1",
  "border-width.2": "--smbk-border-width-2",
  "border-width.3": "--smbk-border-width-3",
  "opacity.media.disabled": "--smbk-opacity-media-disabled",
  "blur.4": "--smbk-blur-4",
  "blur.8": "--smbk-blur-8",
  "blur.14": "--smbk-blur-14",
  "radius.control.xs": "--smbk-radius-control-xs",
  "radius.control.sm": "--smbk-radius-control-sm",
  "radius.control.md": "--smbk-radius-control-md",
  "radius.control.lg": "--smbk-radius-control-lg",
  "radius.container.sm": "--smbk-radius-container-sm",
  "radius.container.md": "--smbk-radius-container-md",
  "radius.container.lg": "--smbk-radius-container-lg",
  "radius.inset": "--smbk-radius-inset",
  "radius.full": "--smbk-radius-full",
  "border-width.hairline": "--smbk-border-width-hairline",
  "border-width.default": "--smbk-border-width-default",
  "border-width.thick": "--smbk-border-width-thick",
  "size.icon.xs": "--smbk-size-icon-xs",
  "size.icon.sm": "--smbk-size-icon-sm",
  "size.icon.md": "--smbk-size-icon-md",
  "size.icon.lg": "--smbk-size-icon-lg",
  "size.icon.xl": "--smbk-size-icon-xl",
  "size.icon.2xl": "--smbk-size-icon-2xl",
  "size.target.min": "--smbk-size-target-min",
  "size.target.comfortable": "--smbk-size-target-comfortable",
  "size.display.xs": "--smbk-size-display-xs",
  "size.display.sm": "--smbk-size-display-sm",
  "size.display.md": "--smbk-size-display-md",
  "size.display.lg": "--smbk-size-display-lg",
  "size.display.xl": "--smbk-size-display-xl",
  "size.selection.sm": "--smbk-size-selection-sm",
  "size.selection.md": "--smbk-size-selection-md",
  "size.selection.lg": "--smbk-size-selection-lg",
  "size.content.sm": "--smbk-size-content-sm",
  "size.content.md": "--smbk-size-content-md",
  "size.content.lg": "--smbk-size-content-lg",
  "size.content.xl": "--smbk-size-content-xl",
  "focus.ring.width": "--smbk-focus-ring-width",
  "focus.ring.offset": "--smbk-focus-ring-offset",
  "typography.display-1": {
    "fontFamily": "--smbk-typography-display-1-font-family",
    "fontSize": "--smbk-typography-display-1-font-size",
    "fontWeight": "--smbk-typography-display-1-font-weight",
    "lineHeight": "--smbk-typography-display-1-line-height",
    "letterSpacing": "--smbk-typography-display-1-letter-spacing",
    "textTransform": "--smbk-typography-display-1-text-transform"
  },
  "typography.display-2": {
    "fontFamily": "--smbk-typography-display-2-font-family",
    "fontSize": "--smbk-typography-display-2-font-size",
    "fontWeight": "--smbk-typography-display-2-font-weight",
    "lineHeight": "--smbk-typography-display-2-line-height",
    "letterSpacing": "--smbk-typography-display-2-letter-spacing",
    "textTransform": "--smbk-typography-display-2-text-transform"
  },
  "typography.h1": {
    "fontFamily": "--smbk-typography-h1-font-family",
    "fontSize": "--smbk-typography-h1-font-size",
    "fontWeight": "--smbk-typography-h1-font-weight",
    "lineHeight": "--smbk-typography-h1-line-height",
    "letterSpacing": "--smbk-typography-h1-letter-spacing",
    "textTransform": "--smbk-typography-h1-text-transform"
  },
  "typography.h2": {
    "fontFamily": "--smbk-typography-h2-font-family",
    "fontSize": "--smbk-typography-h2-font-size",
    "fontWeight": "--smbk-typography-h2-font-weight",
    "lineHeight": "--smbk-typography-h2-line-height",
    "letterSpacing": "--smbk-typography-h2-letter-spacing",
    "textTransform": "--smbk-typography-h2-text-transform"
  },
  "typography.h3": {
    "fontFamily": "--smbk-typography-h3-font-family",
    "fontSize": "--smbk-typography-h3-font-size",
    "fontWeight": "--smbk-typography-h3-font-weight",
    "lineHeight": "--smbk-typography-h3-line-height",
    "letterSpacing": "--smbk-typography-h3-letter-spacing",
    "textTransform": "--smbk-typography-h3-text-transform"
  },
  "typography.h4": {
    "fontFamily": "--smbk-typography-h4-font-family",
    "fontSize": "--smbk-typography-h4-font-size",
    "fontWeight": "--smbk-typography-h4-font-weight",
    "lineHeight": "--smbk-typography-h4-line-height",
    "letterSpacing": "--smbk-typography-h4-letter-spacing",
    "textTransform": "--smbk-typography-h4-text-transform"
  },
  "typography.h5": {
    "fontFamily": "--smbk-typography-h5-font-family",
    "fontSize": "--smbk-typography-h5-font-size",
    "fontWeight": "--smbk-typography-h5-font-weight",
    "lineHeight": "--smbk-typography-h5-line-height",
    "letterSpacing": "--smbk-typography-h5-letter-spacing",
    "textTransform": "--smbk-typography-h5-text-transform"
  },
  "typography.h6": {
    "fontFamily": "--smbk-typography-h6-font-family",
    "fontSize": "--smbk-typography-h6-font-size",
    "fontWeight": "--smbk-typography-h6-font-weight",
    "lineHeight": "--smbk-typography-h6-line-height",
    "letterSpacing": "--smbk-typography-h6-letter-spacing",
    "textTransform": "--smbk-typography-h6-text-transform"
  },
  "typography.subtitle": {
    "fontFamily": "--smbk-typography-subtitle-font-family",
    "fontSize": "--smbk-typography-subtitle-font-size",
    "fontWeight": "--smbk-typography-subtitle-font-weight",
    "lineHeight": "--smbk-typography-subtitle-line-height",
    "letterSpacing": "--smbk-typography-subtitle-letter-spacing",
    "textTransform": "--smbk-typography-subtitle-text-transform"
  },
  "typography.subheading": {
    "fontFamily": "--smbk-typography-subheading-font-family",
    "fontSize": "--smbk-typography-subheading-font-size",
    "fontWeight": "--smbk-typography-subheading-font-weight",
    "lineHeight": "--smbk-typography-subheading-line-height",
    "letterSpacing": "--smbk-typography-subheading-letter-spacing",
    "textTransform": "--smbk-typography-subheading-text-transform"
  },
  "typography.body-l": {
    "fontFamily": "--smbk-typography-body-l-font-family",
    "fontSize": "--smbk-typography-body-l-font-size",
    "fontWeight": "--smbk-typography-body-l-font-weight",
    "lineHeight": "--smbk-typography-body-l-line-height",
    "letterSpacing": "--smbk-typography-body-l-letter-spacing",
    "textTransform": "--smbk-typography-body-l-text-transform"
  },
  "typography.body-m": {
    "fontFamily": "--smbk-typography-body-m-font-family",
    "fontSize": "--smbk-typography-body-m-font-size",
    "fontWeight": "--smbk-typography-body-m-font-weight",
    "lineHeight": "--smbk-typography-body-m-line-height",
    "letterSpacing": "--smbk-typography-body-m-letter-spacing",
    "textTransform": "--smbk-typography-body-m-text-transform"
  },
  "typography.body-s": {
    "fontFamily": "--smbk-typography-body-s-font-family",
    "fontSize": "--smbk-typography-body-s-font-size",
    "fontWeight": "--smbk-typography-body-s-font-weight",
    "lineHeight": "--smbk-typography-body-s-line-height",
    "letterSpacing": "--smbk-typography-body-s-letter-spacing",
    "textTransform": "--smbk-typography-body-s-text-transform"
  },
  "typography.body-t": {
    "fontFamily": "--smbk-typography-body-t-font-family",
    "fontSize": "--smbk-typography-body-t-font-size",
    "fontWeight": "--smbk-typography-body-t-font-weight",
    "lineHeight": "--smbk-typography-body-t-line-height",
    "letterSpacing": "--smbk-typography-body-t-letter-spacing",
    "textTransform": "--smbk-typography-body-t-text-transform"
  },
  "typography.label-l": {
    "fontFamily": "--smbk-typography-label-l-font-family",
    "fontSize": "--smbk-typography-label-l-font-size",
    "fontWeight": "--smbk-typography-label-l-font-weight",
    "lineHeight": "--smbk-typography-label-l-line-height",
    "letterSpacing": "--smbk-typography-label-l-letter-spacing",
    "textTransform": "--smbk-typography-label-l-text-transform"
  },
  "typography.label-m": {
    "fontFamily": "--smbk-typography-label-m-font-family",
    "fontSize": "--smbk-typography-label-m-font-size",
    "fontWeight": "--smbk-typography-label-m-font-weight",
    "lineHeight": "--smbk-typography-label-m-line-height",
    "letterSpacing": "--smbk-typography-label-m-letter-spacing",
    "textTransform": "--smbk-typography-label-m-text-transform"
  },
  "typography.label-s": {
    "fontFamily": "--smbk-typography-label-s-font-family",
    "fontSize": "--smbk-typography-label-s-font-size",
    "fontWeight": "--smbk-typography-label-s-font-weight",
    "lineHeight": "--smbk-typography-label-s-line-height",
    "letterSpacing": "--smbk-typography-label-s-letter-spacing",
    "textTransform": "--smbk-typography-label-s-text-transform"
  },
  "elevation.0": "--smbk-elevation-0",
  "elevation.1": "--smbk-elevation-1",
  "elevation.2": "--smbk-elevation-2",
  "elevation.3": "--smbk-elevation-3",
  "elevation.inset": "--smbk-elevation-inset",
  "elevation.inset-2": "--smbk-elevation-inset-2",
  "layer.base": "--smbk-layer-base",
  "layer.raised": "--smbk-layer-raised",
  "layer.sticky": "--smbk-layer-sticky",
  "layer.overlay": "--smbk-layer-overlay",
  "layer.modal": "--smbk-layer-modal",
  "layer.critical": "--smbk-layer-critical",
  "size.sidebar.width": "--smbk-size-sidebar-width",
  "size.modal.sm": "--smbk-size-modal-sm",
  "size.modal.md": "--smbk-size-modal-md",
  "size.modal.lg": "--smbk-size-modal-lg",
  "size.drawer.width": "--smbk-size-drawer-width",
  "size.dropdown.width": "--smbk-size-dropdown-width",
  "size.command-palette.width": "--smbk-size-command-palette-width",
  "size.search.width": "--smbk-size-search-width",
  "size.preview.narrow": "--smbk-size-preview-narrow",
  "size.table-of-contents.width": "--smbk-size-table-of-contents-width",
  "size.popover.width": "--smbk-size-popover-width",
  "breakpoint.text-size": "--smbk-breakpoint-text-size",
  "breakpoint.layout": "--smbk-breakpoint-layout",
  "breakpoint.side-columns": "--smbk-breakpoint-side-columns",
  "typography.body-l-bold": {
    "fontFamily": "--smbk-typography-body-l-bold-font-family",
    "fontSize": "--smbk-typography-body-l-bold-font-size",
    "fontWeight": "--smbk-typography-body-l-bold-font-weight",
    "lineHeight": "--smbk-typography-body-l-bold-line-height",
    "letterSpacing": "--smbk-typography-body-l-bold-letter-spacing",
    "textTransform": "--smbk-typography-body-l-bold-text-transform"
  },
  "typography.body-m-bold": {
    "fontFamily": "--smbk-typography-body-m-bold-font-family",
    "fontSize": "--smbk-typography-body-m-bold-font-size",
    "fontWeight": "--smbk-typography-body-m-bold-font-weight",
    "lineHeight": "--smbk-typography-body-m-bold-line-height",
    "letterSpacing": "--smbk-typography-body-m-bold-letter-spacing",
    "textTransform": "--smbk-typography-body-m-bold-text-transform"
  },
  "typography.body-s-bold": {
    "fontFamily": "--smbk-typography-body-s-bold-font-family",
    "fontSize": "--smbk-typography-body-s-bold-font-size",
    "fontWeight": "--smbk-typography-body-s-bold-font-weight",
    "lineHeight": "--smbk-typography-body-s-bold-line-height",
    "letterSpacing": "--smbk-typography-body-s-bold-letter-spacing",
    "textTransform": "--smbk-typography-body-s-bold-text-transform"
  },
  "typography.body-m-medium": {
    "fontFamily": "--smbk-typography-body-m-medium-font-family",
    "fontSize": "--smbk-typography-body-m-medium-font-size",
    "fontWeight": "--smbk-typography-body-m-medium-font-weight",
    "lineHeight": "--smbk-typography-body-m-medium-line-height",
    "letterSpacing": "--smbk-typography-body-m-medium-letter-spacing",
    "textTransform": "--smbk-typography-body-m-medium-text-transform"
  },
  "typography.body-m-semibold": {
    "fontFamily": "--smbk-typography-body-m-semibold-font-family",
    "fontSize": "--smbk-typography-body-m-semibold-font-size",
    "fontWeight": "--smbk-typography-body-m-semibold-font-weight",
    "lineHeight": "--smbk-typography-body-m-semibold-line-height",
    "letterSpacing": "--smbk-typography-body-m-semibold-letter-spacing",
    "textTransform": "--smbk-typography-body-m-semibold-text-transform"
  },
  "typography.body-s-semibold": {
    "fontFamily": "--smbk-typography-body-s-semibold-font-family",
    "fontSize": "--smbk-typography-body-s-semibold-font-size",
    "fontWeight": "--smbk-typography-body-s-semibold-font-weight",
    "lineHeight": "--smbk-typography-body-s-semibold-line-height",
    "letterSpacing": "--smbk-typography-body-s-semibold-letter-spacing",
    "textTransform": "--smbk-typography-body-s-semibold-text-transform"
  },
  "typography.body-l-light": {
    "fontFamily": "--smbk-typography-body-l-light-font-family",
    "fontSize": "--smbk-typography-body-l-light-font-size",
    "fontWeight": "--smbk-typography-body-l-light-font-weight",
    "lineHeight": "--smbk-typography-body-l-light-line-height",
    "letterSpacing": "--smbk-typography-body-l-light-letter-spacing",
    "textTransform": "--smbk-typography-body-l-light-text-transform"
  },
  "typography.h4-light": {
    "fontFamily": "--smbk-typography-h4-light-font-family",
    "fontSize": "--smbk-typography-h4-light-font-size",
    "fontWeight": "--smbk-typography-h4-light-font-weight",
    "lineHeight": "--smbk-typography-h4-light-line-height",
    "letterSpacing": "--smbk-typography-h4-light-letter-spacing",
    "textTransform": "--smbk-typography-h4-light-text-transform"
  },
  "duration.80": "--smbk-duration-80",
  "duration.150": "--smbk-duration-150",
  "duration.200": "--smbk-duration-200",
  "duration.320": "--smbk-duration-320",
  "duration.1000": "--smbk-duration-1000",
  "duration.1600": "--smbk-duration-1600",
  "duration.2400": "--smbk-duration-2400",
  "duration.22000": "--smbk-duration-22000",
  "easing.expo-out": "--smbk-easing-expo-out",
  "easing.expo-in": "--smbk-easing-expo-in",
  "easing.cubic-in-out": "--smbk-easing-cubic-in-out",
  "motion.feedback.duration": "--smbk-motion-feedback-duration",
  "motion.feedback.easing": "--smbk-motion-feedback-easing",
  "motion.state.duration": "--smbk-motion-state-duration",
  "motion.state.easing": "--smbk-motion-state-easing",
  "motion.enter.duration": "--smbk-motion-enter-duration",
  "motion.enter.easing": "--smbk-motion-enter-easing",
  "motion.exit.duration": "--smbk-motion-exit-duration",
  "motion.exit.easing": "--smbk-motion-exit-easing",
  "motion.stagger.delay": "--smbk-motion-stagger-delay",
  "motion.hover.open-delay": "--smbk-motion-hover-open-delay",
  "motion.hover.close-delay": "--smbk-motion-hover-close-delay",
  "motion.marquee.duration": "--smbk-motion-marquee-duration",
  "motion.live-pulse.duration": "--smbk-motion-live-pulse-duration",
  "motion.live-pulse.easing": "--smbk-motion-live-pulse-easing",
  "motion.loading.duration": "--smbk-motion-loading-duration",
  "motion.loading.easing": "--smbk-motion-loading-easing",
  "motion.cursor.duration": "--smbk-motion-cursor-duration",
  "motion.ambient.duration": "--smbk-motion-ambient-duration",
  "motion.ambient.easing": "--smbk-motion-ambient-easing",
  "color.surface.canvas": "--smbk-color-surface-canvas",
  "color.surface.default": "--smbk-color-surface-default",
  "color.surface.default-disabled": "--smbk-color-surface-default-disabled",
  "color.surface.raised": "--smbk-color-surface-raised",
  "color.surface.brand": "--smbk-color-surface-brand",
  "color.surface.inverse": "--smbk-color-surface-inverse",
  "color.surface.sunken": "--smbk-color-surface-sunken",
  "color.surface.overlay": "--smbk-color-surface-overlay",
  "color.surface.overlay-subtle": "--smbk-color-surface-overlay-subtle",
  "color.text.default": "--smbk-color-text-default",
  "color.text.subtle": "--smbk-color-text-subtle",
  "color.text.subtlest": "--smbk-color-text-subtlest",
  "color.text.disabled": "--smbk-color-text-disabled",
  "color.text.brand": "--smbk-color-text-brand",
  "color.text.brand-hover": "--smbk-color-text-brand-hover",
  "color.text.accent": "--smbk-color-text-accent",
  "color.text.accent-hover": "--smbk-color-text-accent-hover",
  "color.text.inverse": "--smbk-color-text-inverse",
  "color.text.on-brand": "--smbk-color-text-on-brand",
  "color.text.on-media": "--smbk-color-text-on-media",
  "color.text.selected": "--smbk-color-text-selected",
  "color.text.link": "--smbk-color-text-link",
  "color.text.link-hover": "--smbk-color-text-link-hover",
  "color.text.link-pressed": "--smbk-color-text-link-pressed",
  "color.text.link-underline": "--smbk-color-text-link-underline",
  "color.text.link-underline-hover": "--smbk-color-text-link-underline-hover",
  "color.text.link-disabled": "--smbk-color-text-link-disabled",
  "color.border.subtle": "--smbk-color-border-subtle",
  "color.border.strong": "--smbk-color-border-strong",
  "color.border.control": "--smbk-color-border-control",
  "color.border.control-hover": "--smbk-color-border-control-hover",
  "color.border.control-disabled": "--smbk-color-border-control-disabled",
  "color.border.control-selected": "--smbk-color-border-control-selected",
  "color.border.focus": "--smbk-color-border-focus",
  "color.border.focus-field": "--smbk-color-border-focus-field",
  "color.border.brand": "--smbk-color-border-brand",
  "color.border.inverse": "--smbk-color-border-inverse",
  "color.border.edge-top": "--smbk-color-border-edge-top",
  "color.border.edge-bottom": "--smbk-color-border-edge-bottom",
  "color.border.edge-highlight": "--smbk-color-border-edge-highlight",
  "color.border.edge-highlight-subtle": "--smbk-color-border-edge-highlight-subtle",
  "color.border.edge-shade": "--smbk-color-border-edge-shade",
  "color.border.edge-shade-subtle": "--smbk-color-border-edge-shade-subtle",
  "color.action.brand.background": "--smbk-color-action-brand-background",
  "color.action.brand.background-hover": "--smbk-color-action-brand-background-hover",
  "color.action.brand.background-pressed": "--smbk-color-action-brand-background-pressed",
  "color.action.brand.background-disabled": "--smbk-color-action-brand-background-disabled",
  "color.action.brand.foreground": "--smbk-color-action-brand-foreground",
  "color.action.brand.foreground-disabled": "--smbk-color-action-brand-foreground-disabled",
  "color.action.brand.border": "--smbk-color-action-brand-border",
  "color.action.brand.border-hover": "--smbk-color-action-brand-border-hover",
  "color.action.brand.border-disabled": "--smbk-color-action-brand-border-disabled",
  "color.action.default.background": "--smbk-color-action-default-background",
  "color.action.default.background-hover": "--smbk-color-action-default-background-hover",
  "color.action.default.background-pressed": "--smbk-color-action-default-background-pressed",
  "color.action.default.background-disabled": "--smbk-color-action-default-background-disabled",
  "color.action.default.foreground": "--smbk-color-action-default-foreground",
  "color.action.default.foreground-hover": "--smbk-color-action-default-foreground-hover",
  "color.action.default.foreground-disabled": "--smbk-color-action-default-foreground-disabled",
  "color.action.default.border": "--smbk-color-action-default-border",
  "color.action.default.border-hover": "--smbk-color-action-default-border-hover",
  "color.action.default.border-disabled": "--smbk-color-action-default-border-disabled",
  "color.action.secondary.background": "--smbk-color-action-secondary-background",
  "color.action.secondary.background-hover": "--smbk-color-action-secondary-background-hover",
  "color.action.secondary.background-pressed": "--smbk-color-action-secondary-background-pressed",
  "color.action.secondary.background-disabled": "--smbk-color-action-secondary-background-disabled",
  "color.action.secondary.foreground": "--smbk-color-action-secondary-foreground",
  "color.action.secondary.foreground-disabled": "--smbk-color-action-secondary-foreground-disabled",
  "color.action.secondary.border": "--smbk-color-action-secondary-border",
  "color.action.secondary.border-hover": "--smbk-color-action-secondary-border-hover",
  "color.action.secondary.border-disabled": "--smbk-color-action-secondary-border-disabled",
  "color.action.tertiary.background": "--smbk-color-action-tertiary-background",
  "color.action.tertiary.background-hover": "--smbk-color-action-tertiary-background-hover",
  "color.action.tertiary.background-pressed": "--smbk-color-action-tertiary-background-pressed",
  "color.action.tertiary.background-disabled": "--smbk-color-action-tertiary-background-disabled",
  "color.action.tertiary.foreground": "--smbk-color-action-tertiary-foreground",
  "color.action.tertiary.foreground-disabled": "--smbk-color-action-tertiary-foreground-disabled",
  "color.action.tertiary.border": "--smbk-color-action-tertiary-border",
  "color.action.tertiary.border-hover": "--smbk-color-action-tertiary-border-hover",
  "color.action.tertiary.border-disabled": "--smbk-color-action-tertiary-border-disabled",
  "color.action.outline.border": "--smbk-color-action-outline-border",
  "color.action.outline.border-hover": "--smbk-color-action-outline-border-hover",
  "color.action.outline.border-pressed": "--smbk-color-action-outline-border-pressed",
  "color.action.outline.border-disabled": "--smbk-color-action-outline-border-disabled",
  "color.action.outline.foreground": "--smbk-color-action-outline-foreground",
  "color.action.outline.foreground-disabled": "--smbk-color-action-outline-foreground-disabled",
  "color.action.outline.background-hover": "--smbk-color-action-outline-background-hover",
  "color.action.outline.background-pressed": "--smbk-color-action-outline-background-pressed",
  "color.action.ghost.background-hover": "--smbk-color-action-ghost-background-hover",
  "color.action.ghost.background-pressed": "--smbk-color-action-ghost-background-pressed",
  "color.action.ghost.foreground": "--smbk-color-action-ghost-foreground",
  "color.action.ghost.foreground-disabled": "--smbk-color-action-ghost-foreground-disabled",
  "color.action.inverse.background": "--smbk-color-action-inverse-background",
  "color.action.inverse.background-hover": "--smbk-color-action-inverse-background-hover",
  "color.action.inverse.background-pressed": "--smbk-color-action-inverse-background-pressed",
  "color.action.inverse.background-disabled": "--smbk-color-action-inverse-background-disabled",
  "color.action.inverse.foreground": "--smbk-color-action-inverse-foreground",
  "color.action.inverse.foreground-disabled": "--smbk-color-action-inverse-foreground-disabled",
  "color.action.inverse.border": "--smbk-color-action-inverse-border",
  "color.action.inverse.border-hover": "--smbk-color-action-inverse-border-hover",
  "color.action.inverse.border-disabled": "--smbk-color-action-inverse-border-disabled",
  "color.action.destructive.background": "--smbk-color-action-destructive-background",
  "color.action.destructive.background-hover": "--smbk-color-action-destructive-background-hover",
  "color.action.destructive.background-pressed": "--smbk-color-action-destructive-background-pressed",
  "color.action.destructive.background-disabled": "--smbk-color-action-destructive-background-disabled",
  "color.action.destructive.foreground": "--smbk-color-action-destructive-foreground",
  "color.action.destructive.foreground-hover": "--smbk-color-action-destructive-foreground-hover",
  "color.action.destructive.foreground-disabled": "--smbk-color-action-destructive-foreground-disabled",
  "color.action.destructive.border": "--smbk-color-action-destructive-border",
  "color.action.destructive.border-hover": "--smbk-color-action-destructive-border-hover",
  "color.action.destructive.border-disabled": "--smbk-color-action-destructive-border-disabled",
  "color.feedback.info.surface": "--smbk-color-feedback-info-surface",
  "color.feedback.info.surface-subtle": "--smbk-color-feedback-info-surface-subtle",
  "color.feedback.info.text-on-surface": "--smbk-color-feedback-info-text-on-surface",
  "color.feedback.info.text-on-subtle": "--smbk-color-feedback-info-text-on-subtle",
  "color.feedback.info.border": "--smbk-color-feedback-info-border",
  "color.feedback.info.border-subtle": "--smbk-color-feedback-info-border-subtle",
  "color.feedback.warning.surface": "--smbk-color-feedback-warning-surface",
  "color.feedback.warning.surface-subtle": "--smbk-color-feedback-warning-surface-subtle",
  "color.feedback.warning.text-on-surface": "--smbk-color-feedback-warning-text-on-surface",
  "color.feedback.warning.text-on-subtle": "--smbk-color-feedback-warning-text-on-subtle",
  "color.feedback.warning.border": "--smbk-color-feedback-warning-border",
  "color.feedback.warning.border-subtle": "--smbk-color-feedback-warning-border-subtle",
  "color.feedback.success.surface": "--smbk-color-feedback-success-surface",
  "color.feedback.success.surface-subtle": "--smbk-color-feedback-success-surface-subtle",
  "color.feedback.success.text-on-surface": "--smbk-color-feedback-success-text-on-surface",
  "color.feedback.success.text-on-subtle": "--smbk-color-feedback-success-text-on-subtle",
  "color.feedback.success.border": "--smbk-color-feedback-success-border",
  "color.feedback.success.border-subtle": "--smbk-color-feedback-success-border-subtle",
  "color.feedback.danger.surface": "--smbk-color-feedback-danger-surface",
  "color.feedback.danger.surface-subtle": "--smbk-color-feedback-danger-surface-subtle",
  "color.feedback.danger.text-on-surface": "--smbk-color-feedback-danger-text-on-surface",
  "color.feedback.danger.text-on-subtle": "--smbk-color-feedback-danger-text-on-subtle",
  "color.feedback.danger.border": "--smbk-color-feedback-danger-border",
  "color.feedback.danger.border-subtle": "--smbk-color-feedback-danger-border-subtle",
  "color.overlay.scrim": "--smbk-color-overlay-scrim",
  "color.shadow.xs": "--smbk-color-shadow-xs",
  "color.shadow.s": "--smbk-color-shadow-s",
  "color.shadow.m": "--smbk-color-shadow-m",
  "color.shadow.l": "--smbk-color-shadow-l",
  "color.shadow.xl": "--smbk-color-shadow-xl",
  "color.icon.default": "--smbk-color-icon-default",
  "color.icon.subtle": "--smbk-color-icon-subtle",
  "color.icon.disabled": "--smbk-color-icon-disabled",
  "color.icon.inverse": "--smbk-color-icon-inverse",
  "space.inset.2xs": "--smbk-space-inset-2xs",
  "space.inset.xs": "--smbk-space-inset-xs",
  "space.inset.sm": "--smbk-space-inset-sm",
  "space.inset.md": "--smbk-space-inset-md",
  "space.inset.lg": "--smbk-space-inset-lg",
  "space.inset.xl": "--smbk-space-inset-xl",
  "space.inset.2xl": "--smbk-space-inset-2xl",
  "space.inset.3xl": "--smbk-space-inset-3xl",
  "space.stack.xs": "--smbk-space-stack-xs",
  "space.stack.sm": "--smbk-space-stack-sm",
  "space.stack.md": "--smbk-space-stack-md",
  "space.stack.lg": "--smbk-space-stack-lg",
  "space.stack.xl": "--smbk-space-stack-xl",
  "space.stack.2xl": "--smbk-space-stack-2xl",
  "space.stack.3xl": "--smbk-space-stack-3xl",
  "space.stack.4xl": "--smbk-space-stack-4xl",
  "space.stack.5xl": "--smbk-space-stack-5xl",
  "space.inline.xs": "--smbk-space-inline-xs",
  "space.inline.sm": "--smbk-space-inline-sm",
  "space.inline.md": "--smbk-space-inline-md",
  "space.inline.lg": "--smbk-space-inline-lg",
  "space.inline.xl": "--smbk-space-inline-xl",
  "space.inline.2xl": "--smbk-space-inline-2xl",
  "space.inline.3xl": "--smbk-space-inline-3xl",
  "space.section.sm": "--smbk-space-section-sm",
  "space.section.md": "--smbk-space-section-md",
  "space.section.lg": "--smbk-space-section-lg",
  "space.gutter.xs": "--smbk-space-gutter-xs",
  "space.gutter.sm": "--smbk-space-gutter-sm",
  "size.control.xs": "--smbk-size-control-xs",
  "size.control.sm": "--smbk-size-control-sm",
  "size.control.md": "--smbk-size-control-md",
  "size.control.lg": "--smbk-size-control-lg",
  "text.display-xl": "--smbk-text-display-xl",
  "text.display-lg": "--smbk-text-display-lg",
  "text.heading-xl": "--smbk-text-heading-xl",
  "text.heading-lg": "--smbk-text-heading-lg",
  "text.heading-md": "--smbk-text-heading-md",
  "text.heading-sm": "--smbk-text-heading-sm",
  "text.heading-xs": "--smbk-text-heading-xs",
  "text.heading-2xs": "--smbk-text-heading-2xs",
  "text.body-lg": "--smbk-text-body-lg",
  "text.body-md": "--smbk-text-body-md",
  "text.body-sm": "--smbk-text-body-sm",
  "text.body-xs": "--smbk-text-body-xs",
  "text.label-lg": "--smbk-text-label-lg",
  "text.label-md": "--smbk-text-label-md",
  "text.label-sm": "--smbk-text-label-sm"
} as const;

export type TokenPath = keyof typeof cssVariables;
